### ISSUE TITLE
GIT - permitted

### ISSUE THREAD

**Issue by SiOleskR** [gomeswes/pomysly_online#3]
When I'm trying push branch to the git I get git-recive-pack not permitted.
You can set right tu push on git for me? Maybe I do some things wrong?

**Comment by gomeswes** [comment]
Oh yeah.. I need to set permission for you probably. I'll check it now how to fix it.

**Comment by gomeswes** [comment]
Done! I added you as a Colaborator to the repository, so now you should be able to push code to it.

**Comment by SiOleskR** [comment]
Is ready. Work.
